//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int SentenceId { get; set; }
        public int Selected { get; set; }
        public int ContainerID { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Sentence Sentence { get; set; }
    }
}
